### ISSUE TITLE
[English report] Warnings during compilation

### ISSUE THREAD

**Issue by quilumipe2** [pangolp/mod-recruit-friend#1]
**CURRENT BEHAVIOUR:**
Compilations printing warnings about a depricated command library

**EXPECTED BLIZZLIKE BEHAVIOUR:**
It should compile with no warnings

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1.  Clone the module into sourcefolder/modules
2.  Compile
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**

**OPERATING SYSTEM:**

Ubuntu linux
![CompileWarnings](https://user-images.githubusercontent.com/92389977/143002665-cba2e48c-1680-4b4f-8a5d-e7bd298f9038.png)

**MODULES:**

**CUSTOMIZATIONS:**

**Comment by pangolp** [comment]
Thank you for the report. I will have to check it out. It's been a long time since I've used the module and the emulator has undergone many positive changes since ChromieCraft came out. So I'll try to compile it and check those warnings.

**Comment by pangolp** [comment]
I apologize for the delay in reviewing the topic, but the truth is that I didn't have a machine with Linux and then, time went by and I forgot about it. Thanks again for the report, but with the last commit, the problem should have been solved.
